USE CSE_4B_465

--Part – A 

--1. Create trigger for printing appropriate message after student registration.
GO
	CREATE OR ALTER TRIGGER MESSAGE_AFTER_REGISTRATION
	ON STUDENTS
	AFTER INSERT
	AS 
	BEGIN
		PRINT 'NEW STUDENT REGISTERED'
	END
GO

DROP TRIGGER MESSAGE_AFTER_REGISTRATION

--2. Create trigger for printing appropriate message after faculty deletion. 
GO
	CREATE OR ALTER TRIGGER MESSAGE_AFTER_DELETION
	ON FACULTY
	AFTER DELETE
	AS 
	BEGIN
		PRINT 'SOME FACULTY DELETED'
	END
GO

DROP TRIGGER MESSAGE_AFTER_DELETION

--3. Create trigger for monitoring all events on course table. (print only appropriate message) 
GO
	CREATE OR ALTER TRIGGER MESSAGE_AFTER_EVENT
	ON COURSE
	AFTER INSERT,UPDATE,DELETE
	AS 
	BEGIN
		PRINT 'SOME EVENT OCCURED'
	END
GO

DROP TRIGGER MESSAGE_AFTER_EVENT

--4. Create trigger for logging data on new student registration in Log table. 
CREATE TABLE LOG(
	LOGMESSAGE VARCHAR(50),
	LEGDATE DATE
)

GO
	CREATE OR ALTER TRIGGER LOG_OF_STUDENTS
	ON STUDENTS
	AFTER INSERT
	AS 
	BEGIN
		INSERT INTO LOG VALUES('STUDENT REGISTERD', GETDATE())
	END
GO

DROP TRIGGER LOG_OF_STUDENTS

--5. Create trigger for auto-uppercasing faculty names. 
GO
	CREATE OR ALTER TRIGGER AUTOUPPERCASING
	ON FACULTY
	AFTER INSERT
	AS 
	BEGIN
		UPDATE FACULTY
		SET FacultyName = UPPER(FacultyName)
		WHERE FacultyID IN (SELECT FacultyID FROM FACULTY)
	END
GO

DROP TRIGGER AUTOUPPERCASING

--6. Create trigger for calculating faculty experience (Note: Add required column in faculty table) 
ALTER TABLE FACULTY
ADD EXPERIENCE INT

GO
	CREATE OR ALTER TRIGGER EXPERIENCE
	ON FACULTY
	AFTER INSERT
	AS
	BEGIN
		DECLARE @JDATE DATE
		SELECT @JDATE = FacultyJoiningDate FROM FACULTY
		UPDATE FACULTY 
		SET EXPERIENCE = (DATEDIFF(YEAR, @JDATE, GETDATE()))
		WHERE FacultyID IN (SELECT FacultyID FROM inserted)
	END
GO

DROP TRIGGER EXPERIENCE

--Part – B 

--7. Create trigger for auto-stamping enrollment dates. 
GO
	CREATE OR ALTER TRIGGER AUTO_STAMPING
	ON FACULTY 
	AFTER INSERT
	AS
	BEGIN
		UPDATE ENROLLMENT
		SET EnrollmentDate = GETDATE()
		WHERE EnrollmentID IN (SELECT EnrollmentID FROM inserted)
	END
GO

DROP TRIGGER AUTO_STAMPING

--8. Create trigger for logging data After course assignment - log course and faculty detail. 
GO
	CREATE OR ALTER TRIGGER LOG_COURSE_FACULTY
	ON COURSE_ASSIGNMENT
	AFTER INSERT
	AS
	BEGIN
		DECLARE @CNAME VARCHAR(20), @FNAME VARCHAR(20)
		SELECT @CNAME = CourseName,
			   @FNAME = FacultyName
		FROM FACULTY JOIN COURSE_ASSIGNMENT 
		ON FACULTY.FacultyID = COURSE_ASSIGNMENT.FacultyID
		JOIN COURSE ON COURSE.CourseID = COURSE_ASSIGNMENT.CourseID

		INSERT INTO LOG VALUES ('FACULTY ' + @FNAME + ' ASSINGED TO COURSE ' + @CNAME, GETDATE())
	END
GO

DROP TRIGGER LOG_COURSE_FACULTY

--Part - C 

--9. Create trigger for updating student phone and print the old and new phone number. 
GO
	CREATE OR ALTER TRIGGER STUPHONENO
	ON STUDENTS
	AFTER UPDATE
	AS
	BEGIN
		DECLARE @OLDNO VARCHAR(15), @NEWNO VARCHAR(15)

		SELECT @OLDNO = StuPhone FROM deleted
		WHERE StudentID IN (SELECT StudentID FROM deleted)

		SELECT @NEWNO = StuPhone FROM inserted
		WHERE StudentID IN (SELECT StudentID FROM inserted)

		PRINT 'STUDENT CHANGED PHONE NO FROM ' + @OLDNO + ' TO ' + @NEWNO
	END
GO

DROP TRIGGER STUPHONENO

--10. Create trigger for updating course credit log old and new credits in log table. 
GO
	CREATE OR ALTER TRIGGER COURSECREDITS
	ON COURSE
	AFTER UPDATE
	AS
	BEGIN
		DECLARE @OLDC VARCHAR(15), @NEWC VARCHAR(15)

		SELECT @OLDC = CourseCredits FROM deleted
		WHERE CourseID IN (SELECT CourseID FROM deleted)

		SELECT @NEWC = CourseCredits FROM inserted
		WHERE CourseID IN (SELECT CourseID FROM inserted)

		INSERT INTO LOG VALUES(
			'COURSE CREDITS CHANGED FROM ' + @OLDC + ' TO ' + @NEWC, GETDATE())
	END
GO

DROP TRIGGER COURSECREDITS

-- EXTRA QUERY:

GO
	CREATE OR ALTER TRIGGER MESSAGE_AS_OPERATION
	ON COURSE
	AFTER INSERT, UPDATE, DELETE
	AS
	BEGIN
		IF (SELECT COUNT(*) FROM inserted) > 0 AND (SELECT COUNT(*) FROM deleted) <= 0
			PRINT 'SOME COURSE INSERTED'

		ELSE IF (SELECT COUNT(*) FROM deleted) > 0 AND (SELECT COUNT(*) FROM inserted) <= 0
			PRINT 'SOME COURSE DELETED'

		ELSE
			PRINT 'SOME COURSE UPDATED'
	END
GO

UPDATE COURSE
SET CourseSemester = 4
WHERE CourseID = '123'

DROP TRIGGER MESSAGE_AS_OPERATION