USE CSE_4B_465

--Part – A 

--1. Create trigger for blocking student deletion.
GO
	CREATE OR ALTER TRIGGER TR_BLOCKING_STUDENT
	ON STUDENTS
	INSTEAD OF DELETE
	AS
	BEGIN
		PRINT('DELETION IS NOT ALLOWED')
	END
GO

DROP TRIGGER TR_BLOCKING_STUDENT

--2. Create trigger for making course read-only. 
GO
	CREATE OR ALTER TRIGGER TR_READ_ONLY
	ON COURSE
	INSTEAD OF INSERT, UPDATE, DELETE
	AS
	BEGIN
		PRINT('COURSE IS NOT MODIFIABLE')
	END
GO

DROP TRIGGER TR_READ_ONLY

--3. Create trigger for preventing faculty removal. 
GO
	CREATE OR ALTER TRIGGER TR_PREVENT_FACULTY_REMOVE
	ON FACULTY
	INSTEAD OF DELETE
	AS
	BEGIN
		PRINT('YOU CAN NOT DELETE FACULTY')
	END
GO

DROP TRIGGER TR_PREVENT_FACULTY_REMOVE

--4. Create instead of trigger to log all operations on COURSE (INSERT/UPDATE/DELETE) into Log table. 
--	 (Example: INSERT/UPDATE/DELETE operations are blocked for you in course table) 
GO
	CREATE OR ALTER TRIGGER TR_LOG_OF_MODIFICATION
	ON COURSE
	INSTEAD OF INSERT, UPDATE, DELETE
	AS
	BEGIN
		INSERT INTO LOG VALUES
		('YOU CAN NOT MODIFY TABLE', GETDATE())
	END
GO

DROP TRIGGER TR_LOG_OF_MODIFICATION

SELECT * FROM LOG

--5. Create trigger to Block student to update their enrollment year and print message ‘students are not 
--	 allowed to update their enrollment year’ 
GO
	CREATE OR ALTER TRIGGER TR_BLOCK_ENROLLMENT
	ON STUDENTS
	INSTEAD OF UPDATE
	AS
	BEGIN
		IF UPDATE(STUENROLLMENTYEAR)
			PRINT('YOU CAN NOT UPDATE ENROLLMENT YEAR')
	END
GO

DROP TRIGGER TR_BLOCK_ENROLLMENT

--6. Create trigger for student age validation (Min 18). 
GO
	CREATE OR ALTER TRIGGER TR_AGE_RESTRICTION
	ON STUDENTS
	INSTEAD OF INSERT
	AS
	BEGIN
		DECLARE @AGE INT
		SELECT @AGE = DATEDIFF(YEAR, STUDATEOFBIRTH, GETDATE())
		FROM inserted

		IF @AGE < 18
			PRINT('YOU ARE UNDER 18')

		ELSE
		BEGIN
			INSERT INTO STUDENTS 
			SELECT * FROM inserted
		END
	END
GO

DROP TRIGGER TR_AGE_RESTRICTION

--Part – B 

--7. Create trigger for unique faculty’s email check. 
GO
	CREATE OR ALTER TRIGGER TR_UNIQUE_EMAIL
	ON FACULTY 
	INSTEAD OF INSERT
	AS
	BEGIN
		DECLARE @EMAIL VARCHAR(50)
		SELECT @EMAIL = FacultyEmail
		FROM inserted

		IF EXISTS (SELECT @EMAIL FROM FACULTY)
			PRINT('INVALID EMAIL')

		ELSE
		BEGIN
			INSERT INTO FACULTY
			SELECT * FROM inserted
		END
	END
GO

DROP TRIGGER TR_UNIQUE_EMAIL

SELECT * FROM FACULTY

INSERT INTO FACULTY VALUES
(111, 'MR.ABC', 'gupta@univ.edu', 'RUBBER', 'ASSISTANT' , '2010-08-01', NULL)

--8. Create trigger for preventing duplicate enrollment. 
GO
	CREATE OR ALTER TRIGGER TR_UNIQUE_ENROLLMENT
	ON ENROLLMENT
	INSTEAD OF INSERT
	AS
	BEGIN
		DECLARE @ENRO INT
		SELECT @ENRO = EnrollmentID
		FROM inserted

		IF EXISTS (SELECT @ENRO FROM ENROLLMENT)
			PRINT('INVALID ENROLLMENT')

		ELSE
		BEGIN
			INSERT INTO ENROLLMENT (StudentID, CourseID, EnrollmentDate, GRADE, EnrollmentStatus)
			SELECT StudentID, CourseID, EnrollmentDate, GRADE, EnrollmentStatus FROM inserted
		END
	END
GO

DROP TRIGGER TR_UNIQUE_ENROLLMENT

--Part - C 

--9. Create trigger to Allow enrolment in month from Jan to August, otherwise print message 
--	 enrolment closed.
GO
	CREATE OR ALTER TRIGGER TR_ENR_TIME
	ON ENROLLMENT 
	INSTEAD OF INSERT
	AS
	BEGIN
		DECLARE @MONTH INT
		SELECT @MONTH = DATEPART(MONTH,ENROLLMENTDATE)
		FROM inserted

		IF @MONTH > 8
			PRINT('NOT AVAILABLE IN THIS MONTH')

		ELSE
		BEGIN
			INSERT INTO ENROLLMENT (StudentID, CourseID, EnrollmentDate, GRADE, EnrollmentStatus)
			SELECT StudentID, CourseID, EnrollmentDate, GRADE, EnrollmentStatus FROM inserted
		END
	END
GO

DROP TRIGGER TR_ENR_TIME

--10. Create trigger to Allow only grade change in enrollment (block other updates) 
GO
	CREATE OR ALTER TRIGGER TR_GRADE_CHANGE
	ON ENROLLMENT
	INSTEAD OF UPDATE
	AS
	BEGIN
		DECLARE @GRADE VARCHAR(50)
		SELECT @GRADE = GRADE
		FROM inserted

		IF UPDATE(GRADE)
		BEGIN
			INSERT INTO ENROLLMENT (StudentID, CourseID, EnrollmentDate, GRADE, EnrollmentStatus)
			SELECT StudentID, CourseID, EnrollmentDate, GRADE, EnrollmentStatus FROM inserted
		END

		ELSE
			PRINT('YOU CAN NOT UPDATE THOSE FIELDS')
	END
GO

DROP TRIGGER TR_GRADE_CHANGE

-- FIRST EXTRA
GO
	CREATE OR ALTER TRIGGER TR_LOG_MESSAGE
	ON COURSE
	INSTEAD OF INSERT, UPDATE, DELETE
	AS
	BEGIN
		IF (SELECT COUNT(*) FROM inserted) > 0 AND (SELECT COUNT(*) FROM deleted) <= 0
			INSERT INTO LOG VALUES
			('SOMEONE TRIED TO INSERT INTO COURSE TABLE', GETDATE())

		ELSE IF (SELECT COUNT(*) FROM deleted) > 0 AND (SELECT COUNT(*) FROM inserted) <= 0
			INSERT INTO LOG VALUES
			('SOMEONE TRIED TO DELETE INTO COURSE TABLE', GETDATE())

		ELSE
			INSERT INTO LOG VALUES
			('SOMEONE TRIED TO UPDATE INTO COURSE TABLE', GETDATE())


		INSERT INTO LOG VALUES
		('YOU CAN NOT MODIFY TABLE', GETDATE())
	END
GO

DROP TRIGGER [MESSAGE_AS_OPERATION]