USE CSE_4B_465

--Part – A 

--1. Create a cursor Course_Cursor to fetch all rows from COURSE table and display them. 
GO
DECLARE @CID VARCHAR(10), @CNAME VARCHAR(10), @CREDITS INT, @DEPT VARCHAR(10), @SEM INT

DECLARE COURSE_CURSOR CURSOR FOR 
SELECT * FROM COURSE

OPEN COURSE_CURSOR

FETCH NEXT FROM COURSE_CURSOR INTO @CID, @CNAME, @CREDITS , @DEPT, @SEM 

WHILE @@FETCH_STATUS = 0
BEGIN
	SELECT @CID AS COURSEID, @CNAME AS COURSE, @CREDITS AS CREDITS, @DEPT AS DEPARTMENT, @SEM AS SEMESTER

	FETCH NEXT FROM COURSE_CURSOR INTO @CID, @CNAME, @CREDITS , @DEPT, @SEM 
END

CLOSE COURSE_CURSOR
DEALLOCATE COURSE_CURSOR
GO

--2. Create a cursor Student_Cursor_Fetch to fetch records in form of StudentID_StudentName 
--   (Example: 1_Raj Patel).
GO

DECLARE @STUID INT, @STUNAME VARCHAR(20)

DECLARE Student_Cursor_Fetch CURSOR FOR
SELECT StudentID, StuName FROM STUDENTS

OPEN STUDENT_CURSOR_FETCH

FETCH NEXT FROM Student_Cursor_Fetch INTO @STUID, @STUNAME

WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT CAST(@STUID AS VARCHAR)+'_'+@STUNAME
	FETCH NEXT FROM Student_Cursor_Fetch INTO @STUID, @STUNAME
END
CLOSE Student_Cursor_Fetch 
DEALLOCATE Student_Cursor_Fetch 

GO

--3. Create a cursor to find and display all courses with Credits greater than 3.
GO

DECLARE @COURSEID VARCHAR(10)

DECLARE COURSE_CREDITS_GREATER_THAN_3 CURSOR FOR
SELECT CourseID FROM COURSE WHERE CourseCredits > 3

OPEN COURSE_CREDITS_GREATER_THAN_3

FETCH NEXT FROM COURSE_CREDITS_GREATER_THAN_3 INTO @COURSEID

WHILE @@FETCH_STATUS = 0
BEGIN
	SELECT COURSENAME FROM COURSE WHERE CourseID = @COURSEID
	FETCH NEXT FROM COURSE_CREDITS_GREATER_THAN_3 INTO @COURSEID
END
CLOSE COURSE_CREDITS_GREATER_THAN_3
DEALLOCATE COURSE_CREDITS_GREATER_THAN_3

GO

SELECT * FROM STUDENTS

--4. Create a cursor to display all students who enrolled in year 2021 or later.
GO

DECLARE @STUID VARCHAR(10)

DECLARE CURSOR_STUDENT_AFTER_2021 CURSOR FOR
SELECT StudentID FROM STUDENTS WHERE StuEnrollmentYear >= 2021

OPEN CURSOR_STUDENT_AFTER_2021

FETCH NEXT FROM CURSOR_STUDENT_AFTER_2021 INTO @STUID

WHILE @@FETCH_STATUS = 0
BEGIN
	SELECT * FROM STUDENTS WHERE StudentID = @STUID
	FETCH NEXT FROM CURSOR_STUDENT_AFTER_2021 INTO @STUID
END

CLOSE CURSOR_STUDENT_AFTER_2021
DEALLOCATE CURSOR_STUDENT_AFTER_2021

GO

--5. Create a cursor Course_CursorUpdate that retrieves all courses and increases Credits by 1 
--   for courses with Credits less than 4. 
GO

DECLARE @COURSEID VARCHAR(10)
DECLARE Course_CursorUpdate CURSOR FOR
SELECT CourseID FROM COURSE WHERE CourseCredits < 4

OPEN Course_CursorUpdate
FETCH NEXT FROM Course_CursorUpdate INTO @COURSEID

WHILE @@FETCH_STATUS = 0
BEGIN
	UPDATE COURSE 
	SET CourseCredits = CourseCredits + 1
	WHERE CourseCredits < 4
END
CLOSE Course_CursorUpdate
DEALLOCATE Course_CursorUpdate

GO

--6. Create a Cursor to fetch Student Name with Course Name (Example: Raj Patel is enrolled in 
--   Database Management System) 
GO

DECLARE @STUNAME VARCHAR(20), @COURSENAME VARCHAR(30)
DECLARE STUDENT_WITH_COURSENAME CURSOR FOR
SELECT StuName,CourseName FROM STUDENTS JOIN ENROLLMENT 
		ON STUDENTS.StudentID = ENROLLMENT.StudentID
		JOIN COURSE ON ENROLLMENT.CourseID = COURSE.CourseID

OPEN STUDENT_WITH_COURSENAME
FETCH NEXT FROM STUDENT_WITH_COURSENAME INTO @STUNAME, @COURSENAME

WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT @STUNAME+' IS ENROLLED IN '+@COURSENAME
	FETCH NEXT FROM STUDENT_WITH_COURSENAME INTO @STUNAME, @COURSENAME

END
CLOSE STUDENT_WITH_COURSENAME
DEALLOCATE STUDENT_WITH_COURSENAME

GO

--7. Create a cursor to insert data into new table if student belong to ‘CSE’ department.
--   (create new table CSEStudent with relevant columns)

CREATE TABLE CSEStudent(
	sname varchar(50),
	sdept varchar(50))

GO
DECLARE @SNAME VARCHAR(50),@SDEPT VARCHAR(50)
DECLARE StudentDept_Cursor_Fetch CURSOR
FOR SELECT StuName,StuDepartment
FROM STUDENTS


OPEN StudentDept_Cursor_Fetch
FETCH NEXT FROM StudentDept_Cursor_Fetch INTO @SNAME,@SDEPT

WHILE @@FETCH_STATUS = 0
BEGIN
	INSERT INTO CSEStudent VALUES (@SNAME ,@SDEPT)
	FETCH NEXT FROM StudentDept_Cursor_Fetch INTO @SNAME,@SDEPT
END
CLOSE StudentDept_Cursor_Fetch
DEALLOCATE StudentDept_Cursor_Fetch
GO
